name: multi_vendor
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0-164.0.dev


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  geocoding: ^3.0.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  provider: ^6.1.2
  get: ^4.6.6
  flutter_vector_icons: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  flutter_hooks: ^0.20.5
  http: ^1.2.2
  shimmer: ^3.0.0
  glass: ^2.0.0+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  get_storage: ^2.1.1
  webview_flutter_android: ^3.16.7
  webview_flutter_wkwebview: ^3.15.0
  device_preview: ^1.2.0
  otp_text_field: ^1.1.3
  #firebase_auth: ^5.2.1
  #firebase_core: ^3.4.1
  country_picker: ^2.0.26
  rive: ^0.13.13
  reusable: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^4.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/anime/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
